version: '3.8'

services:
  app:
    image: app:react
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_container
    volumes:
      - .:/core
      - /core/node_modules
    ports:
      - 5173:5173
    command: npm run dev
